POST http://localhost:3001/api/games
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvcnRzdSIsImlkIjoiNjNiZmQ1NWFhYzE4ZWZhZTk5YWI5NzgyIiwiaWF0IjoxNjczNTE3MTU0LCJleHAiOjE2ODEyOTMxNTR9.vwdmI0lzWInqfrVvXpI7qUBmu-nnfoYEbEPqbf8IP8o


{
    "players": [
        "63bfd55aac18efae99ab9782",
        "63bfd55eac18efae99ab9784"
    ],
    "rounds": [
        [14, 12],
        [12, 2],
        [2, 12]
    ],
    "sport": "63b98adce2358774d28e761d"
}