name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: environment variables
      env:
        SECRET: ${{ secrets.SECRET }}
        MONGO_URL_TEST: ${{ secrets.MONGO_URL_TEST }}
    - uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - run: npm install
    - run: npm run test
